#!/usr/bin/env python3
"""S3a diagnostic ratchet. No production baseline is generated by this tool."""

import argparse
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
import sys
import uuid

from adapter_runner import Scanner, assess, scan
from config_guard import verify
from git_state import GitState
from measure import write


class Options(argparse.Namespace):
    command: str = ''
    base: str = ''
    out: Path = Path('.quality/reports')
    timeout: float = 1800


def main(argv: list[str] | None = None, root: Path | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    _ = parser.add_argument(
        'command',
        choices=['verify-config', 'clippy', 'shellcheck', 'python-types', 'audit'],
    )
    _ = parser.add_argument('--base', required=True)
    _ = parser.add_argument('--out', type=Path, default=Path('.quality/reports'))
    _ = parser.add_argument('--timeout', type=float, default=1800)
    options = Options()
    _ = parser.parse_args(argv, namespace=options)
    repository = root or Path(__file__).resolve().parents[1]
    output: Path | None = None
    try:
        # Output inside the checkout must be ignored, or the final clean check fails.
        out_root = (
            options.out if options.out.is_absolute() else repository / options.out
        )
        output = out_root.resolve() / (
            datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%S')
            + '-'
            + uuid.uuid4().hex
        )
        output.mkdir(parents=True)
        state = GitState(repository, options.base)
        verify(state)
        write(
            output / 'provenance.json',
            {
                'base': state.base,
                'head': state.head,
                'command': options.command,
                'python': sys.version,
            },
        )
        if options.command == 'verify-config':
            write(
                output / 'result.json',
                {'status': 'configuration-unchanged', 'exit_code': 0},
            )
            return 0
        findings = scan(
            options.command, state, Scanner(state.root, output, options.timeout)
        )
        result = assess(options.command, findings, state)
        state.require_clean()
        write(output / 'findings.json', [asdict(finding) for finding in findings])
        status = {
            'new': [
                {**asdict(finding), 'count': count}
                for finding, count in sorted(result.new.items())
            ],
            'stale': [
                {**asdict(finding), 'count': count}
                for finding, count in sorted(result.stale.items())
            ],
        }
        code = 0 if result.clean else 1
        write(output / 'result.json', {**status, 'exit_code': code})
        print(output)
        return code
    # This CLI boundary converts unexpected parser failures to setup failure.
    # KeyboardInterrupt/SystemExit remain outside Exception.
    except Exception as exc:
        if output is not None:
            write(output / 'result.json', {'error': str(exc), 'exit_code': 2})
        print('ratchet: ' + str(exc), file=sys.stderr)
        return 2


if __name__ == '__main__':
    sys.exit(main())
